apiVersion: v1
kind: Secret
metadata:
  name: uss-secrets
  namespace: uss-prod
type: Opaque
stringData:
  USS_BOOTSTRAP_ADMIN_TOKEN: change-me-admin-token
  USS_WORKER_SHARED_SECRET: change-me-worker-secret
  USS_PLATFORM_SERVICES_API_TOKEN: change-me-platform-token
